# Generated by Django 5.2.8 on 2025-11-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('suffix', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('birthDate', models.DateTimeField(auto_now_add=True)),
                ('middleName', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('contactNumber', models.CharField(max_length=50)),
                ('completeAddress', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('educAttainment', models.CharField(max_length=200)),
                ('schoolAddress', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=100)),
                ('tesdaCert', models.CharField(max_length=200)),
                ('ncipTribe', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=100)),
                ('milTraining', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
