# Generated by Django 5.2.8 on 2025-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthDate',
            field=models.CharField(max_length=50),
        ),
    ]
