# Generated by Django 5.2.8 on 2025-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_applicant_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='completeAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contactNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='educAttainment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='eligibility',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='height',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='middleName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='milTraining',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ncipTribe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='religion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='schoolAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='suffix',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='tesdaCert',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
