# Generated by Django 5.2.8 on 2025-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_applicant_age_alter_applicant_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='select one...', max_length=10),
        ),
    ]
