# Generated by Django 5.2.8 on 2025-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_applicant_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
