# Generated by Django 5.2.8 on 2025-12-05 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cycle_processingcenter_purpose_treatmentfacility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purpose'),
        ),
    ]
