# Generated by Django 5.2.8 on 2025-12-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_applicant_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cycle'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mtf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.treatmentfacility'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.processingcenter'),
        ),
    ]
