# Generated by Django 5.2.8 on 2025-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_applicant_cycle_applicant_mtf_applicant_pc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name_plural': 'Applicant'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'verbose_name_plural': 'Cycle'},
        ),
        migrations.AlterModelOptions(
            name='processingcenter',
            options={'verbose_name_plural': 'Processing Center'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name_plural': 'Purpose'},
        ),
        migrations.AlterModelOptions(
            name='treatmentfacility',
            options={'verbose_name_plural': 'Treatment Facility'},
        ),
        migrations.AlterField(
            model_name='processingcenter',
            name='pcCode',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentfacility',
            name='mtfCode',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
