# Generated by Django 5.2.8 on 2025-12-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_applicant_options_alter_cycle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingcenter',
            name='pcCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
